#page title
page_title                                : Meshy                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6746294698                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id6746294698                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Meshy                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 0                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create stunning abstract wallpapers and backgrounds with this powerful mesh gradient editor.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Meshy Team
your_link                                 : https://meshy.karmaacademy.com.au
your_city                                 : Brisbane
email_address                             : 
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : 
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Interactive Gradient Editor
    description                           : Create mesh gradients with draggable control points, multiple gradient types, and real-time color editing
    fontawesome_icon_name                 : edit

  - title                                 : Multiple Export Formats
    description                           : Export high-resolution wallpapers to Photos app with multiple aspect ratios and resolution options
    fontawesome_icon_name                 : download

  - title                                 : Advanced Customization
    description                           : Precise color control, template library, multiple interpolation methods, and adjustable mesh complexity
    fontawesome_icon_name                 : palette

  - title                                 : Premium Features
    description                           : Access advanced export options, extended template library, and additional customization tools
    fontawesome_icon_name                 : star

faqs                                      :

  - title                                 : How do I create a gradient wallpaper?
    description                           : Use the interactive editor to drag control points, choose colors, and adjust the mesh complexity to create your gradient
    fontawesome_icon_name                 : image

  - title                                 : What export formats are supported?
    description                           : Export wallpapers in multiple resolutions and aspect ratios including Square, 4:3, 16:9, and Phone Story formats
    fontawesome_icon_name                 : mobile

  - title                                 : How can I save my gradient settings?
    description                           : Export gradient data as JSON or copy settings to clipboard for easy sharing and transfer between devices
    fontawesome_icon_name                 : save

  - title                                 : How do I contact for support?
    description                           : You can reach out to support@karmaacademy.com.au for support requests and technical assistance
    fontawesome_icon_name                 : users

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"





####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
include: [".well-known"]
